<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AssemblyName>SinglePureResource</AssemblyName>
    <RootNamespace>SinglePureResource</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Library.fs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="SinglePureResource.pure.json" LogicalName="SinglePureResource.pure.json" />
  </ItemGroup>
</Project>
