namespace FSharp.PureAnalyzer

open System

/// Heuristic rules that classify BCL / FSharp.Core members as impure by name
/// or by well-known side-effecting surface area. These seed List A analysis
/// before the recursive call-graph walk.
module ImpurityRules =

    /// Namespace / type prefixes that are treated as inherently impure.
    let private impureTypePrefixes =
        [|
            "System.IO."
            "System.Net."
            "System.Threading."
            "System.Diagnostics."
            "System.Console"
            "System.Environment"
            "System.Random"
            "System.Security.Cryptography."
            "Microsoft.Win32."
            "System.Runtime.InteropServices."
            "System.Reflection.Emit."
        |]

    /// Exact type names considered impure (any member).
    let private impureTypes =
        set
            [
                "System.Console"
                "System.Environment"
                "System.Random"
                "System.DateTime"
                "System.DateTimeOffset"
                "System.Guid"
                "System.GC"
                "System.Threading.Thread"
                "System.Threading.Tasks.Task"
                "System.Threading.Tasks.Task`1"
                "System.Diagnostics.Debug"
                "System.Diagnostics.Trace"
                "System.Diagnostics.Process"
            ]

    /// Method name suffixes / exact names that indicate impurity even on
    /// otherwise pure-looking types (mutation, I/O, non-determinism).
    let private impureMethodNames =
        set
            [
                "Write"
                "WriteLine"
                "WriteAsync"
                "WriteLineAsync"
                "Read"
                "ReadLine"
                "ReadAsync"
                "Flush"
                "FlushAsync"
                "Close"
                "Dispose"
                "DisposeAsync"
                "Set"
                "Add"
                "Remove"
                "Clear"
                "Insert"
                "SetValue"
                "CopyTo"
                "GetHashCode" // intentionally excluded from pure set: identity-sensitive
            ]

    /// Well-known pure BCL / FSharp.Core leaf primitives that have no useful
    /// IL body (intrinsics, JIT helpers) or are pure by language definition.
    /// These bootstrap the recursive purity fixed-point.
    let knownPureLeaves: Set<string> =
        set
            [
                // Arithmetic / operators (FSharp.Core)
                "Microsoft.FSharp.Core.Operators.op_Addition"
                "Microsoft.FSharp.Core.Operators.op_Subtraction"
                "Microsoft.FSharp.Core.Operators.op_Multiply"
                "Microsoft.FSharp.Core.Operators.op_Division"
                "Microsoft.FSharp.Core.Operators.op_Modulus"
                "Microsoft.FSharp.Core.Operators.op_UnaryNegation"
                "Microsoft.FSharp.Core.Operators.op_UnaryPlus"
                "Microsoft.FSharp.Core.Operators.op_LessThan"
                "Microsoft.FSharp.Core.Operators.op_GreaterThan"
                "Microsoft.FSharp.Core.Operators.op_LessThanOrEqual"
                "Microsoft.FSharp.Core.Operators.op_GreaterThanOrEqual"
                "Microsoft.FSharp.Core.Operators.op_Equality"
                "Microsoft.FSharp.Core.Operators.op_Inequality"
                "Microsoft.FSharp.Core.Operators.op_Append"
                "Microsoft.FSharp.Core.Operators.not"
                "Microsoft.FSharp.Core.Operators.id"
                "Microsoft.FSharp.Core.Operators.ignore"
                "Microsoft.FSharp.Core.Operators.fst"
                "Microsoft.FSharp.Core.Operators.snd"
                "Microsoft.FSharp.Core.Operators.abs"
                "Microsoft.FSharp.Core.Operators.sign"
                "Microsoft.FSharp.Core.Operators.floor"
                "Microsoft.FSharp.Core.Operators.ceil"
                "Microsoft.FSharp.Core.Operators.round"
                "Microsoft.FSharp.Core.Operators.sqrt"
                "Microsoft.FSharp.Core.Operators.log"
                "Microsoft.FSharp.Core.Operators.log10"
                "Microsoft.FSharp.Core.Operators.exp"
                "Microsoft.FSharp.Core.Operators.sin"
                "Microsoft.FSharp.Core.Operators.cos"
                "Microsoft.FSharp.Core.Operators.tan"
                "Microsoft.FSharp.Core.Operators.asin"
                "Microsoft.FSharp.Core.Operators.acos"
                "Microsoft.FSharp.Core.Operators.atan"
                "Microsoft.FSharp.Core.Operators.atan2"
                "Microsoft.FSharp.Core.Operators.pown"
                "Microsoft.FSharp.Core.Operators.min"
                "Microsoft.FSharp.Core.Operators.max"
                "Microsoft.FSharp.Core.Operators.compare"
                "Microsoft.FSharp.Core.Operators.hash"
                "Microsoft.FSharp.Core.Operators.box"
                "Microsoft.FSharp.Core.Operators.unbox"
                "Microsoft.FSharp.Core.Operators.byte"
                "Microsoft.FSharp.Core.Operators.sbyte"
                "Microsoft.FSharp.Core.Operators.int16"
                "Microsoft.FSharp.Core.Operators.uint16"
                "Microsoft.FSharp.Core.Operators.int"
                "Microsoft.FSharp.Core.Operators.int32"
                "Microsoft.FSharp.Core.Operators.uint32"
                "Microsoft.FSharp.Core.Operators.int64"
                "Microsoft.FSharp.Core.Operators.uint64"
                "Microsoft.FSharp.Core.Operators.nativeint"
                "Microsoft.FSharp.Core.Operators.unativeint"
                "Microsoft.FSharp.Core.Operators.float"
                "Microsoft.FSharp.Core.Operators.float32"
                "Microsoft.FSharp.Core.Operators.double"
                "Microsoft.FSharp.Core.Operators.single"
                "Microsoft.FSharp.Core.Operators.decimal"
                "Microsoft.FSharp.Core.Operators.char"
                "Microsoft.FSharp.Core.Operators.string"
                "Microsoft.FSharp.Core.ExtraTopLevelOperators.dict"
                "Microsoft.FSharp.Core.ExtraTopLevelOperators.set"
                "Microsoft.FSharp.Core.ExtraTopLevelOperators.array2D"
                "Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.GetArray"
                "Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.GetArray2D"
                "Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.GetArray3D"
                "Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.GetArray4D"
                "Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.TypeTestGeneric"
                "Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.TypeTestFast"
                "Microsoft.FSharp.Core.LanguagePrimitives.GenericEquality"
                "Microsoft.FSharp.Core.LanguagePrimitives.GenericComparison"
                "Microsoft.FSharp.Core.LanguagePrimitives.GenericHash"
                "Microsoft.FSharp.Core.LanguagePrimitives.FastGenericComparer"
                "Microsoft.FSharp.Core.LanguagePrimitives.FastGenericEqualityComparer"
                "Microsoft.FSharp.Core.LanguagePrimitives.ParseInt32"
                "Microsoft.FSharp.Core.LanguagePrimitives.ParseInt64"
                "Microsoft.FSharp.Core.LanguagePrimitives.ParseUInt32"
                "Microsoft.FSharp.Core.LanguagePrimitives.ParseUInt64"
                "Microsoft.FSharp.Core.LanguagePrimitives.EnumOfValue"
                "Microsoft.FSharp.Core.LanguagePrimitives.EnumToValue"
                // Option / Result / Choice basics
                "Microsoft.FSharp.Core.OptionModule.Map"
                "Microsoft.FSharp.Core.OptionModule.Bind"
                "Microsoft.FSharp.Core.OptionModule.Exists"
                "Microsoft.FSharp.Core.OptionModule.Forall"
                "Microsoft.FSharp.Core.OptionModule.Filter"
                "Microsoft.FSharp.Core.OptionModule.Flatten"
                "Microsoft.FSharp.Core.OptionModule.IsSome"
                "Microsoft.FSharp.Core.OptionModule.IsNone"
                "Microsoft.FSharp.Core.OptionModule.DefaultValue"
                "Microsoft.FSharp.Core.OptionModule.DefaultWith"
                "Microsoft.FSharp.Core.OptionModule.OrElse"
                "Microsoft.FSharp.Core.OptionModule.OrElseWith"
                "Microsoft.FSharp.Core.OptionModule.ToArray"
                "Microsoft.FSharp.Core.OptionModule.ToList"
                "Microsoft.FSharp.Core.OptionModule.OfNullable"
                "Microsoft.FSharp.Core.OptionModule.ToNullable"
                "Microsoft.FSharp.Core.OptionModule.Count"
                "Microsoft.FSharp.Core.OptionModule.Fold"
                "Microsoft.FSharp.Core.OptionModule.FoldBack"
                "Microsoft.FSharp.Core.OptionModule.Contains"
                "Microsoft.FSharp.Core.ResultModule.Map"
                "Microsoft.FSharp.Core.ResultModule.MapError"
                "Microsoft.FSharp.Core.ResultModule.Bind"
                "Microsoft.FSharp.Core.ResultModule.IsOk"
                "Microsoft.FSharp.Core.ResultModule.IsError"
                "Microsoft.FSharp.Core.ResultModule.DefaultValue"
                "Microsoft.FSharp.Core.ResultModule.DefaultWith"
                // Core BCL pure surface
                "System.String.Concat"
                "System.String.Join"
                "System.String.Format"
                "System.String.IsNullOrEmpty"
                "System.String.IsNullOrWhiteSpace"
                "System.String.Equals"
                "System.String.Compare"
                "System.String.CompareOrdinal"
                "System.String.Contains"
                "System.String.StartsWith"
                "System.String.EndsWith"
                "System.String.IndexOf"
                "System.String.LastIndexOf"
                "System.String.Substring"
                "System.String.Trim"
                "System.String.TrimStart"
                "System.String.TrimEnd"
                "System.String.ToLower"
                "System.String.ToUpper"
                "System.String.ToLowerInvariant"
                "System.String.ToUpperInvariant"
                "System.String.Replace"
                "System.String.PadLeft"
                "System.String.PadRight"
                "System.String.Split"
                "System.String.Insert"
                "System.String.Remove"
                "System.String.Normalize"
                "System.String.IsNormalized"
                "System.String.Copy"
                "System.String.Intern"
                "System.String.IsInterned"
                "System.String.ToCharArray"
                "System.String.get_Length"
                "System.String.get_Chars"
                "System.String.op_Equality"
                "System.String.op_Inequality"
                "System.Math.Abs"
                "System.Math.Max"
                "System.Math.Min"
                "System.Math.Sign"
                "System.Math.Sqrt"
                "System.Math.Pow"
                "System.Math.Log"
                "System.Math.Log10"
                "System.Math.Log2"
                "System.Math.Exp"
                "System.Math.Sin"
                "System.Math.Cos"
                "System.Math.Tan"
                "System.Math.Asin"
                "System.Math.Acos"
                "System.Math.Atan"
                "System.Math.Atan2"
                "System.Math.Floor"
                "System.Math.Ceiling"
                "System.Math.Round"
                "System.Math.Truncate"
                "System.Math.IEEERemainder"
                "System.Math.BigMul"
                "System.Math.DivRem"
                "System.Math.Clamp"
                "System.Math.CopySign"
                "System.Math.FusedMultiplyAdd"
                "System.Math.BitDecrement"
                "System.Math.BitIncrement"
                "System.Math.ReciprocalEstimate"
                "System.Math.ReciprocalSqrtEstimate"
                "System.Math.ScaleB"
                "System.Math.ILogB"
                "System.Convert.ToInt32"
                "System.Convert.ToInt64"
                "System.Convert.ToDouble"
                "System.Convert.ToSingle"
                "System.Convert.ToDecimal"
                "System.Convert.ToBoolean"
                "System.Convert.ToByte"
                "System.Convert.ToSByte"
                "System.Convert.ToInt16"
                "System.Convert.ToUInt16"
                "System.Convert.ToUInt32"
                "System.Convert.ToUInt64"
                "System.Convert.ToChar"
                "System.Convert.ToString"
                "System.Convert.ChangeType"
                "System.Object.Equals"
                "System.Object.ReferenceEquals"
                "System.Object.ToString"
                "System.ValueType.Equals"
                "System.ValueType.GetHashCode"
                "System.ValueType.ToString"
                "System.Enum.Equals"
                "System.Enum.ToString"
                "System.Enum.GetName"
                "System.Enum.GetNames"
                "System.Enum.GetValues"
                "System.Enum.IsDefined"
                "System.Enum.Parse"
                "System.Enum.TryParse"
                "System.Enum.ToObject"
                "System.Enum.HasFlag"
                "System.Nullable`1.get_HasValue"
                "System.Nullable`1.get_Value"
                "System.Nullable`1.GetValueOrDefault"
                "System.Nullable`1.Equals"
                "System.Nullable`1.GetHashCode"
                "System.Nullable`1.ToString"
                "System.MemoryExtensions.AsSpan"
                "System.MemoryExtensions.AsMemory"
                "System.Span`1.get_Length"
                "System.Span`1.get_IsEmpty"
                "System.Span`1.get_Item"
                "System.ReadOnlySpan`1.get_Length"
                "System.ReadOnlySpan`1.get_IsEmpty"
                "System.ReadOnlySpan`1.get_Item"
                "System.Array.Empty"
                "System.Array.IndexOf"
                "System.Array.LastIndexOf"
                "System.Array.BinarySearch"
                "System.Array.Exists"
                "System.Array.Find"
                "System.Array.FindAll"
                "System.Array.FindIndex"
                "System.Array.FindLast"
                "System.Array.FindLastIndex"
                "System.Array.TrueForAll"
                "System.Array.ConvertAll"
                "System.Array.TrueForAll"
                "System.Array.get_Length"
                "System.Array.get_LongLength"
                "System.Array.get_Rank"
                "System.Array.GetLength"
                "System.Array.GetLongLength"
                "System.Array.GetLowerBound"
                "System.Array.GetUpperBound"
                "System.Array.GetValue"
                "System.Array.Clone"
                "System.Char.IsDigit"
                "System.Char.IsLetter"
                "System.Char.IsWhiteSpace"
                "System.Char.IsLetterOrDigit"
                "System.Char.IsUpper"
                "System.Char.IsLower"
                "System.Char.IsPunctuation"
                "System.Char.IsSymbol"
                "System.Char.IsControl"
                "System.Char.IsNumber"
                "System.Char.IsSeparator"
                "System.Char.IsSurrogate"
                "System.Char.IsHighSurrogate"
                "System.Char.IsLowSurrogate"
                "System.Char.ToUpper"
                "System.Char.ToLower"
                "System.Char.ToUpperInvariant"
                "System.Char.ToLowerInvariant"
                "System.Char.IsAscii"
                "System.Char.IsAsciiDigit"
                "System.Char.IsAsciiHexDigit"
                "System.Char.IsAsciiLetter"
                "System.Char.IsAsciiLetterLower"
                "System.Char.IsAsciiLetterUpper"
                "System.Char.GetNumericValue"
                "System.Char.GetUnicodeCategory"
                "System.Char.ConvertFromUtf32"
                "System.Char.ConvertToUtf32"
                "System.Char.ToString"
                "System.Char.Equals"
                "System.Char.CompareTo"
                "System.Boolean.Parse"
                "System.Boolean.TryParse"
                "System.Boolean.ToString"
                "System.Boolean.Equals"
                "System.Boolean.CompareTo"
                "System.Int32.Parse"
                "System.Int32.TryParse"
                "System.Int32.ToString"
                "System.Int32.Equals"
                "System.Int32.CompareTo"
                "System.Int32.Abs"
                "System.Int32.Clamp"
                "System.Int32.IsEvenInteger"
                "System.Int32.IsOddInteger"
                "System.Int32.IsPow2"
                "System.Int32.Log2"
                "System.Int32.LeadingZeroCount"
                "System.Int32.TrailingZeroCount"
                "System.Int32.PopCount"
                "System.Int32.RotateLeft"
                "System.Int32.RotateRight"
                "System.Int64.Parse"
                "System.Int64.TryParse"
                "System.Int64.ToString"
                "System.Int64.Equals"
                "System.Int64.CompareTo"
                "System.Double.Parse"
                "System.Double.TryParse"
                "System.Double.ToString"
                "System.Double.Equals"
                "System.Double.CompareTo"
                "System.Double.IsNaN"
                "System.Double.IsInfinity"
                "System.Double.IsFinite"
                "System.Double.IsNegative"
                "System.Double.IsPositive"
                "System.Double.IsNormal"
                "System.Double.IsSubnormal"
                "System.Double.IsNegativeInfinity"
                "System.Double.IsPositiveInfinity"
                "System.Decimal.Parse"
                "System.Decimal.TryParse"
                "System.Decimal.ToString"
                "System.Decimal.Equals"
                "System.Decimal.CompareTo"
                "System.Decimal.Add"
                "System.Decimal.Subtract"
                "System.Decimal.Multiply"
                "System.Decimal.Divide"
                "System.Decimal.Remainder"
                "System.Decimal.Negate"
                "System.Decimal.Floor"
                "System.Decimal.Ceiling"
                "System.Decimal.Truncate"
                "System.Decimal.Round"
                "System.Decimal.Compare"
                "System.TimeSpan.FromTicks"
                "System.TimeSpan.FromSeconds"
                "System.TimeSpan.FromMinutes"
                "System.TimeSpan.FromHours"
                "System.TimeSpan.FromDays"
                "System.TimeSpan.FromMilliseconds"
                "System.TimeSpan.Parse"
                "System.TimeSpan.TryParse"
                "System.TimeSpan.ToString"
                "System.TimeSpan.Equals"
                "System.TimeSpan.CompareTo"
                "System.TimeSpan.Add"
                "System.TimeSpan.Subtract"
                "System.TimeSpan.Duration"
                "System.TimeSpan.Negate"
                "System.TimeSpan.get_Ticks"
                "System.TimeSpan.get_Days"
                "System.TimeSpan.get_Hours"
                "System.TimeSpan.get_Minutes"
                "System.TimeSpan.get_Seconds"
                "System.TimeSpan.get_Milliseconds"
                "System.TimeSpan.get_TotalDays"
                "System.TimeSpan.get_TotalHours"
                "System.TimeSpan.get_TotalMinutes"
                "System.TimeSpan.get_TotalSeconds"
                "System.TimeSpan.get_TotalMilliseconds"
                "System.Uri.TryCreate"
                "System.Uri.EscapeDataString"
                "System.Uri.UnescapeDataString"
                "System.Uri.EscapeUriString"
                "System.Uri.get_Scheme"
                "System.Uri.get_Host"
                "System.Uri.get_Port"
                "System.Uri.get_AbsolutePath"
                "System.Uri.get_AbsoluteUri"
                "System.Uri.get_Query"
                "System.Uri.get_Fragment"
                "System.Uri.get_IsAbsoluteUri"
                "System.Uri.ToString"
                "System.Uri.Equals"
                "System.Version.Parse"
                "System.Version.TryParse"
                "System.Version.ToString"
                "System.Version.Equals"
                "System.Version.CompareTo"
                "System.Guid.Parse"
                "System.Guid.TryParse"
                "System.Guid.ToString"
                "System.Guid.Equals"
                "System.Guid.CompareTo"
                "System.Guid.ToByteArray"
                "System.Guid.Empty"
            ]

    let private startsWithAny (value: string) (prefixes: string array) =
        prefixes
        |> Array.exists (fun p -> value.StartsWith(p, StringComparison.Ordinal))

    /// Returns Some reason when the declaring type is considered impure.
    let typeImpurityReason (typeFullName: string) : string option =
        if impureTypes.Contains typeFullName then
            Some $"Type '{typeFullName}' is classified as impure"
        elif startsWithAny typeFullName impureTypePrefixes then
            Some $"Type '{typeFullName}' is under an impure namespace prefix"
        else
            None

    /// Returns true when a method name alone is a strong impurity signal
    /// (used only together with other evidence, not as a sole veto for pure types).
    let isImpureMethodName (methodName: string) : bool = impureMethodNames.Contains methodName

    /// Strip generic arity markers and method signature suffixes for matching.
    let normalizeName (fullName: string) : string =
        let noSig =
            match fullName.IndexOf '(' with
            | -1 -> fullName
            | i -> fullName.Substring(0, i)

        // Drop generic arity `N on types/methods for leaf matching.
        let builder = System.Text.StringBuilder(noSig.Length)
        let mutable i = 0

        while i < noSig.Length do
            let c = noSig[i]

            if c = '`' then
                i <- i + 1

                while i < noSig.Length && System.Char.IsDigit noSig[i] do
                    i <- i + 1
            else
                builder.Append c |> ignore
                i <- i + 1

        builder.ToString()

    let isKnownPureLeaf (fullName: string) : bool =
        let n = normalizeName fullName
        knownPureLeaves.Contains n || knownPureLeaves.Contains fullName
