#!/usr/bin/env bash
# Apply fspure → fstarter integration pack into a local fstarter checkout.
#
# Usage:
#   bash scripts/prepare-fstarter-update.sh /path/to/fstarter [analyzer-version]
#
# Writes:
#   .devcontainer/setup-fspure.sh
#   .devcontainer/devcontainer.json   (fspure-enabled settings; keeps other .devcontainer files)
#   .devcontainer/fspure-versions.env
#   .fspure-sync-source (metadata)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PACK="$ROOT/integrations/fstarter"
OVERLAY="$PACK/overlay"
VERSIONS_FILE="$PACK/versions.env"

FSTARTER="${1:-}"
ANALYZER_VERSION_ARG="${2:-}"

die() { echo "ERROR: $*" >&2; exit 1; }

[[ -n "$FSTARTER" && -d "$FSTARTER" ]] || die "usage: $0 /path/to/fstarter [analyzer-version]"
[[ -d "$OVERLAY/.devcontainer" ]] || die "missing overlay at $OVERLAY"

# Resolve analyzer version
if [[ -n "$ANALYZER_VERSION_ARG" ]]; then
  ANALYZER_VERSION="$ANALYZER_VERSION_ARG"
elif [[ -n "${FSPURE_ANALYZER_VERSION:-}" ]]; then
  ANALYZER_VERSION="$FSPURE_ANALYZER_VERSION"
elif [[ -f "$VERSIONS_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$VERSIONS_FILE"
  ANALYZER_VERSION="${FSPURE_ANALYZER_VERSION:-0.4.0}"
else
  ANALYZER_VERSION="0.4.0"
fi

DC="$FSTARTER/.devcontainer"
mkdir -p "$DC"

# Copy fspure-owned files only (do not delete Dockerfile, newf.sh, etc.).
cp -f "$OVERLAY/.devcontainer/setup-fspure.sh" "$DC/setup-fspure.sh"
chmod +x "$DC/setup-fspure.sh"

if [[ -f "$OVERLAY/.devcontainer/devcontainer.json" ]]; then
  cp -f "$OVERLAY/.devcontainer/devcontainer.json" "$DC/devcontainer.json"
fi

# Version pin consumed by setup-fspure.sh
{
  echo "# Generated by e-St/fspure prepare-fstarter-update.sh — do not edit by hand in fstarter."
  echo "# Source of truth: e-St/fspure integrations/fstarter/versions.env"
  echo "FSPURE_ANALYZER_VERSION=${ANALYZER_VERSION}"
} >"$DC/fspure-versions.env"

# Ensure analyzers/ is gitignored (Ionide drop).
if [[ -f "$FSTARTER/.gitignore" ]]; then
  if ! grep -qE '^(\*\*/)?analyzers/?$' "$FSTARTER/.gitignore" 2>/dev/null; then
    printf '\n# fspure / Ionide analyzer drop\n**/analyzers/\n' >>"$FSTARTER/.gitignore"
  fi
else
  printf '# fspure / Ionide analyzer drop\n**/analyzers/\n' >"$FSTARTER/.gitignore"
fi

# Sync metadata for humans / CI
{
  echo "source_repo=e-St/fspure"
  echo "source_path=integrations/fstarter"
  echo "source_sha=${GITHUB_SHA:-local}"
  echo "source_ref=${GITHUB_REF:-local}"
  echo "fspure_analyzer_version=${ANALYZER_VERSION}"
  echo "synced_at_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  if [[ -n "${GITHUB_SERVER_URL:-}" && -n "${GITHUB_REPOSITORY:-}" && -n "${GITHUB_RUN_ID:-}" ]]; then
    echo "workflow_run=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
  fi
  echo "method=pull-request"
} >"$FSTARTER/.fspure-sync-source"

echo "Prepared fstarter update in: $FSTARTER"
echo "  FSPURE_ANALYZER_VERSION=$ANALYZER_VERSION"
echo "  files:"
echo "    .devcontainer/setup-fspure.sh"
echo "    .devcontainer/devcontainer.json"
echo "    .devcontainer/fspure-versions.env"
echo "    .fspure-sync-source"
echo "    .gitignore (analyzers/ ensure)"
